### ISSUE TITLE
Level filtering

### ISSUE THREAD

**Issue by jvantillo** [Travix-International/logger#3]
In Loggy (https://github.com/Travix-International/loggy/blob/master/Loggy.go) we've got a feature where logging is filtered by level, e.g. no debug level on production. This is achieved by using a (configurable) minimum level plus the `github.com/hashicorp/logutils` package.

Level filtering is very useful to reduce the size of the logs on production, I feel we should include this. Do we want to apply this this per-transport, or for all transports equally?

**Comment by fahad19** [comment]
JavaScript implementation has it at Transport-level: https://github.com/Travix-International/travix-logger#console

**Comment by jvantillo** [comment]
Yeah it's what I'd favor as well.
